[project]
name = "google-cloud-bucket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv>=1.0.0",
    "google-cloud-storage>=3.9.0",
]
